#  Copyright (c) 2019, Build-A-Cell. All rights reserved.
#  See LICENSE file in the project root directory for details.

import copy
from numbers import Real
from typing import List, Union
from warnings import warn

from ..mechanisms.global_mechanisms import GlobalMechanism
from .compartment import Compartment
from .mechanism import Mechanism
from .parameter import Parameter, ParameterDatabase, ParameterKey
from .species import Species


class Component:
    """Base class for biomolecular components in BioCRNpyler.

    Component subclasses represent different kinds of biomolecules such as
    DNA, RNA, proteins, and complexes. Components interact with mechanism
    objects to generate chemical reaction network (CRN) species and reactions
    during compilation. This class must be subclassed to provide functionality
    by overriding the `update_species` and `update_reactions` methods.

    Parameters
    ----------
    name : str or Species
        Name of the component. If a `Species` object is provided, its name
        attribute will be used.
    mechanisms : dict or list, optional
        Custom mechanisms to override default mechanisms from the mixture.
        Can be a dict with mechanism types (str) as keys and mechanism
        objects as values, or a list of mechanism objects.
    parameters : dict, optional
        Dictionary of parameter values to add to the component's parameter
        database. Keys follow the format (mechanism, part_id, param_name).
    parameter_file : str, optional
        Path to a parameter file (CSV or TSV format) to load into the
        component's parameter database.
    mixture : Mixture, optional
        Reference to the `Mixture` object containing this component. The
        mixture provides default mechanisms and parameters.
    compartment : Compartment, optional
        The `Compartment` object representing the physical location of this
        component.
    attributes : list of str, optional
        List of attribute strings to tag the component and its associated
        species. Attributes can be used for mechanism selection and species
        filtering.
    initial_concentration : float, optional
        Initial concentration of the component's primary species. Must be
        non-negative. This value is added to the parameter database with key
        ('initial concentration', None, component.name).
    initial_condition_dictionary : dict, optional
        Dictionary mapping species (or species names) to initial concentration
        values for components with multiple species.

    Attributes
    ----------
    name : str
        The name of the component.
    mechanisms : dict
        Dictionary of mechanisms specific to this component, keyed by
        mechanism type (str).
    mixture : Mixture or None
        Reference to the mixture containing this component.
    compartment : Compartment or None
        The compartment containing this component.
    attributes : list of str
        List of attribute tags associated with this component.
    parameter_database : ParameterDatabase
        Database storing all parameters associated with this component.
    initial_concentration : float or None
        Initial concentration value for the component's primary species.
    initial_condition_dictionary : dict
        Dictionary of initial conditions for species generated by this
        component.

    See Also
    --------
    Mechanism : Base class for reaction generation schemas.
    Mixture : Container for components, mechanisms, and global parameters.
    Species : Represents chemical species in a CRN.

    Notes
    -----
    This is an abstract base class. Direct instantiation is possible but
    subclasses like `DNA`, `RNA`, `Protein`, or `DNAassembly` should be
    used for specific biomolecular functionality.

    The parameter lookup hierarchy is:

    1. Component.parameter_database
    2. Component.mixture.parameter_database (if mixture is set)

    Examples
    --------
    Create a basic component with custom parameters:

    >>> comp = bcp.Component(
    ...     name='MyComponent',
    ...     parameters={'kb': 100, 'ku': 10},
    ...     initial_concentration=50.0
    ... )
    >>> comp.name
    'MyComponent'

    """

    def __init__(
        self,
        name: Union[str, Species],
        mechanisms=None,  # custom mechanisms
        parameters=None,  # parameter configuration
        parameter_file=None,  # custom parameter file
        mixture=None,
        compartment=None,
        attributes=None,
        # This is added as a parameter ("initial concentration",
        # None, self.name):initial_concentration
        initial_concentration=None,
        initial_condition_dictionary=None,
    ):
        if mechanisms is None:
            self.mechanisms = {}
        else:
            self.mechanisms = mechanisms
        if isinstance(name, Species):
            self.name = name.name
        elif isinstance(name, str):
            self.name = name
        else:
            raise ValueError("name must be a Species or string")

        # Attributes can be used to store key words like protein deg-tags for
        # components that mimic CRN species.
        self.attributes = []
        self.set_attributes(attributes)
        self.set_mixture(mixture)

        if compartment is not None:
            if not isinstance(compartment, Compartment):
                raise TypeError(
                    "The compartment must be a Compartment object"
                )
            self.compartment = compartment
        else:
            # Don't create default compartment here to avoid circular imports
            self._compartment = None

        self.parameter_database = ParameterDatabase(
            parameter_file=parameter_file, parameter_dictionary=parameters
        )
        self.initial_concentration = initial_concentration

        # Components can also store initial conditions, just like Mixtures
        if initial_condition_dictionary is None:
            self.initial_condition_dictionary = {}
        else:
            self.initial_condition_dictionary = dict(
                initial_condition_dictionary
            )

    @property
    def initial_concentration(self):
        return self._initial_concentration

    @initial_concentration.setter
    def initial_concentration(self, initial_concentration):
        if initial_concentration is not None:
            if initial_concentration < 0:
                raise ValueError(
                    f"Initial concentration must be non-negative, "
                    f"this was given: {initial_concentration}"
                )
            param_key = ParameterKey(
                mechanism='initial concentration',
                part_id=None,
                name=self.name,
            )
            self.parameter_database.add_parameter(
                parameter_name='initial concentration',
                parameter_value=initial_concentration,
                parameter_key=param_key,
                overwrite_parameters=True,
            )

        self._initial_concentration = initial_concentration

    @property
    def compartment(self):
        """Compartment or None: The compartment containing this component."""
        return self._compartment

    @compartment.setter
    def compartment(self, compartment: Compartment) -> None:
        """Set the compartment of the component.

        Parameters
        ----------
        compartment : Compartment
            The compartment object to assign to this component. Also updates
            any internal species with default compartments.

        """
        if compartment is not None and not isinstance(
            compartment, Compartment
        ):
            raise TypeError("The compartment must be a Compartment object")
        if compartment is not None:
            self._compartment = compartment
        if hasattr(self, '_compartment') and self._compartment:
            if hasattr(self, 'species'):
                if isinstance(self.species, list):
                    for s in self.species:
                        if s.compartment.name == 'default':
                            s.compartment = compartment
                else:
                    if self.species.compartment.name == 'default':
                        self.species.compartment = compartment
        if compartment is not None and not isinstance(
            compartment, Compartment
        ):
            raise TypeError("The compartment must be a Compartment object")

    def set_mixture(self, mixture) -> None:
        """Set the mixture containing this component.

        Parameters
        ----------
        mixture : Mixture or None
            The mixture object that contains this component and provides
            default mechanisms and parameters.

        """
        self.mixture = mixture

    # TODO implement as an abstractmethod
    def get_species(self) -> None:
        """Get the primary species associated with this component.

        Returns
        -------
        None
            Subclasses should override this method to return their primary
            `Species` object.

        Notes
        -----
        This is a placeholder that should be implemented by subclasses.

        """
        return None

    @classmethod
    def set_species(
        self,
        species: Union[Species, str],
        material_type=None,
        compartment=None,
        attributes=None,
    ) -> Species:
        """Convert various inputs into Species objects.

        Parameters
        ----------
        species : Species, str, Component, or list
            The species to convert. Can be a `Species` object (returned
            as-is), a string (creates new Species), a `Component` (extracts
            its species), or a list of any of these types.
        material_type : str, optional
            Material type for the species (e.g., 'dna', 'rna', 'protein').
            Only used when creating new Species from strings.
        compartment : Compartment, optional
            Compartment to assign to the species. Only used when creating
            new Species from strings.
        attributes : list of str, optional
            Attributes to assign to the species. Only used when creating
            new Species from strings.

        Returns
        -------
        Species or list of Species
            The converted Species object(s). Returns a list if input was a
            list.

        Raises
        ------
        ValueError
            If the input cannot be converted to a valid Species.

        """
        if isinstance(species, Species):
            return species
        elif isinstance(species, str):
            return Species(
                name=species,
                material_type=material_type,
                compartment=compartment,
                attributes=attributes,
            )
        elif (
            isinstance(species, Component)
            and species.get_species() is not None
        ):
            return species.get_species()
        elif isinstance(species, list):
            return [
                self.set_species(
                    s,
                    material_type=material_type,
                    compartment=compartment,
                    attributes=attributes,
                )
                for s in species
            ]
        else:
            raise ValueError(
                "Invalid Species: string, chemical_reaction_network.Species "
                "or Component with implemented .get_species() required "
                f"as input. Recieved {species}"
            )

    def __hash__(self):
        return str.__hash__(repr(self.get_species()))

    def set_attributes(self, attributes: List[str]):
        """Set multiple attributes for the component.

        Adds a list of attribute tags to the component and its associated
        species by calling `add_attribute` for each attribute in the list.

        Parameters
        ----------
        attributes : list of str or None
            List of attribute strings to add to the component. If None, no
            action is taken.

        See Also
        --------
        add_attribute : Add a single attribute to the component.

        Examples
        --------
        >>> comp = bcp.Protein(name="MyProtein")
        >>> comp.set_attributes(["degtagged", "fluorescent"])
        >>> comp.attributes
        ['degtagged', 'fluorescent']

        """
        if attributes is not None:
            for attribute in attributes:
                self.add_attribute(attribute)

    def add_attribute(self, attribute: str):
        """Add a single attribute to the component.

        Adds an attribute tag to the component's attribute list and to its
        associated species object, if one exists. Attributes can be used for
        mechanism selection, species filtering, and tracking special
        properties.

        Parameters
        ----------
        attribute : str
            Attribute string to add to the component. Must be a non-None
            string value.

        Raises
        ------
        AssertionError
            If `attribute` is not a string or is None.
        Warning
            If the component has no internal species to which the attribute
            can be added.

        Notes
        -----
        Attributes are commonly used to tag components with properties such
        as:

        - Degradation tags (e.g., 'degtagged', 'ssrAtagged', )
        - Functional properties (e.g., 'fluorescent', 'membranebound')
        - Regulatory elements (e.g., 'inducible', 'repressible')

        Examples
        --------
        Add attributes to tag a protein with special properties:

        >>> protein = bcp.Protein('GFP')
        >>> protein.add_attribute('fluorescent')
        >>> protein.add_attribute('ssrAtagged')
        >>> protein.attributes
        ['fluorescent', 'ssrAtagged']

        """
        assert isinstance(attribute, str) and attribute is not None, (
            f"Attribute: {attribute} must be a str"
        )

        self.attributes.append(attribute)
        if hasattr(self, 'species') and self.species is not None:
            self.species.add_attribute(attribute)
        else:
            raise Warning(
                f"Component {self.name} has no internal species and "
                "therefore no attributes"
            )

    def update_parameters(
        self,
        parameter_file=None,
        parameters=None,
        parameter_database=None,
        overwrite_parameters=True,
    ):
        """Update the parameter database with new parameters.

        Parameters
        ----------
        parameter_file : str, optional
            Path to a CSV or TSV file containing parameters to load.
        parameters : dict, optional
            Dictionary of parameters to add. Keys follow the format
            (mechanism, part_id, param_name).
        parameter_database : ParameterDatabase, optional
            Another parameter database to merge into component's database.
        overwrite_parameters : bool, default=True
            If True, new parameter values overwrite existing ones. If False,
            existing parameters are preserved.

        """
        if parameter_file is not None:
            self.parameter_database.load_parameters_from_file(
                parameter_file, overwrite_parameters=overwrite_parameters
            )

        if parameters is not None:
            self.parameter_database.load_parameters_from_dictionary(
                parameters, overwrite_parameters=overwrite_parameters
            )

        if parameter_database is not None:
            self.parameter_database.load_parameters_from_database(
                parameter_database, overwrite_parameters=overwrite_parameters
            )

    def get_mechanism(self, mechanism_type, optional_mechanism=False):
        """Retrieve a mechanism by type from the component or its mixture.

        Searches first in the component's mechanism dictionary, then falls
        back to the mixture's mechanisms if not found.

        Parameters
        ----------
        mechanism_type : str
            The type identifier of the mechanism to retrieve (e.g.,
            'transcription', 'translation', 'binding').
        optional_mechanism : bool, default=False
            If True, returns None when mechanism not found. If False, raises
            KeyError when mechanism not found.

        Returns
        -------
        Mechanism or None
            The requested mechanism object, or None if not found and
            `optional_mechanism` is True.

        Raises
        ------
        TypeError
            If `mechanism_type` is not a string.
        KeyError
            If mechanism not found and `optional_mechanism` is False.

        """
        if not isinstance(mechanism_type, str):
            raise TypeError(
                f"mechanism_type must be a string. Received {mechanism_type}."
            )

        mech = None
        if mechanism_type in self.mechanisms:
            return self.mechanisms[mechanism_type]
        elif self.mixture is not None:
            mech = self.mixture.get_mechanism(mechanism_type)
        if mech is None and not optional_mechanism:
            raise KeyError(
                f"Unable to find mechanism of type {mechanism_type} in "
                f"Component {self} or Mixture {self.mixture}."
            )
        else:
            return mech

    @property
    def mechanisms(self):
        return self._mechanisms

    @mechanisms.setter
    def mechanisms(self, mechanisms):
        self._mechanisms = {}
        if isinstance(mechanisms, dict):
            for mech_type in mechanisms:
                self.add_mechanism(
                    mechanisms[mech_type], mech_type, overwrite=True
                )
        elif isinstance(mechanisms, list):
            for mech in mechanisms:
                self.add_mechanism(mech, overwrite=True)

    def add_mechanism(
        self,
        mechanism: Mechanism,
        mech_type=None,
        overwrite=False,
        optional_mechanism=False,
    ):
        """Add a mechanism to this component's mechanism dictionary.

        Parameters
        ----------
        mechanism : Mechanism
            The mechanism object to add.
        mech_type : str, optional
            The type key under which to store the mechanism. If None, uses
            the mechanism's `mechanism_type` attribute.
        overwrite : bool, default=False
            If True, replaces any existing mechanism with the same key.
            If False, raises ValueError when key already exists.
        optional_mechanism : bool, default=False
            If True, suppresses the ValueError when a mechanism key conflict
            occurs and `overwrite` is False.

        Raises
        ------
        TypeError
            If `mechanism` is not a Mechanism object, or if `mech_type` is
            not a string.
        ValueError
            If mechanism key already exists, `overwrite` is False, and
            `optional_mechanism` is False.

        """
        if not hasattr(self, '_mechanisms'):
            self._mechanisms = {}

        if not isinstance(mechanism, Mechanism):
            raise TypeError(
                f"mechanism must be a Mechanism. Received {mechanism}."
            )

        if mech_type is None:
            mech_type = mechanism.mechanism_type
        if not isinstance(mech_type, str):
            raise TypeError(
                f"mechanism keys must be strings. Received {mech_type}"
            )

        if mech_type not in self._mechanisms or overwrite:
            self._mechanisms[mech_type] = copy.deepcopy(mechanism)
        elif not optional_mechanism:
            raise ValueError(
                f"mech_type {mech_type} already in component {self}. "
                "To overwrite, use keyword overwrite=True."
            )

    def add_mechanisms(
        self,
        mechanisms: Union[Mechanism, GlobalMechanism],
        overwrite=False,
        optional_mechanism=False,
    ):
        """Add multiple mechanisms to this component.

        Accepts mechanisms as a single object, list, or dictionary and adds
        them to the component's mechanism dictionary.

        Parameters
        ----------
        mechanisms : Mechanism, GlobalMechanism, dict, or list
            The mechanism(s) to add. Can be a single mechanism, a dict with
            mechanism types as keys and mechanisms as values, or a list of
            mechanisms.
        overwrite : bool, default=False
            If True, replaces any existing mechanisms with the same keys.
            If False, raises ValueError when keys already exist.
        optional_mechanism : bool, default=False
            If True, suppresses ValueError when mechanism key conflicts occur
            and `overwrite` is False.

        Raises
        ------
        ValueError
            If `mechanisms` is not a valid type, or if mechanism key conflicts
            occur with `overwrite=False` and `optional_mechanism=False`.

        """
        if isinstance(mechanisms, Mechanism):
            self.add_mechanism(
                mechanisms,
                overwrite=overwrite,
                optional_mechanism=optional_mechanism,
            )
        elif isinstance(mechanisms, dict):
            for mech_type in mechanisms:
                self.add_mechanism(
                    mechanisms[mech_type],
                    mech_type,
                    overwrite=overwrite,
                    optional_mechanism=optional_mechanism,
                )
        elif isinstance(mechanisms, list):
            for mech in mechanisms:
                self.add_mechanism(
                    mech,
                    overwrite=overwrite,
                    optional_mechanism=optional_mechanism,
                )
        else:
            raise ValueError(
                f"add_mechanisms expected a list of Mechanisms. "
                f"Received {mechanisms}"
            )

    def get_parameter(
        self,
        param_name: str,
        part_id=None,
        mechanism=None,
        return_numerical=False,
        return_none=False,
        check_mixture=True,
        check_mechanism=True,
    ) -> Union[Parameter, Real]:
        """Retrieve parameter from component or mixture parameter database.

        Searches first in the component's parameter database, then falls back
        to the mixture's parameter database if not found.

        Parameters
        ----------
        param_name : str
            Name of the parameter to retrieve.
        part_id : str, optional
            Part identifier for the parameter lookup key.
        mechanism : str, optional
            Mechanism identifier for the parameter lookup key.
        return_numerical : bool, default=False
            If True, returns the numerical value. If False, returns the
            `Parameter` object.
        return_none : bool, default=False
            If True, returns None when parameter not found. If False, raises
            ValueError when parameter not found.
        check_mixture : bool, default=True
            If True, searches the mixture's parameter database if not found
            in the component's database.
        check_mechanism : bool, default=True
            If True, searches the mechanism's parameter database if not found
            in the component or mixture database.

        Returns
        -------
        Parameter, Real, or None
            The parameter object or its numerical value, or None if not found
            and `return_none` is True.

        Raises
        ------
        ValueError
            If parameter not found and `return_none` is False.

        Notes
        -----
        Parameter lookup follows the hierarchy:

        1. Component.parameter_database
        2. Component.mixture.parameter_database (if `check_mixture` is True)
        3. Component.mechanism.parameter_database (if `check_mechanism`
           is True)

        """
        # Try the Component ParameterDatabase
        param = self.parameter_database.find_parameter(
            mechanism, part_id, param_name
        )

        # Next try the Mixture ParameterDatabase
        if param is None and self.mixture is not None and check_mixture:
            param = self.mixture.get_parameter(mechanism, part_id, param_name)

        # Finally, try the mechanism parameter database
        if param is None and self.mechanisms is not None and check_mechanism:
            if self.mechanisms.get(mechanism, None):
                param = self.mechanisms[mechanism].get_parameter(
                    mechanism, part_id, param_name
                )

        if param is None and not return_none:
            raise ValueError(
                "No parameters can be found that match the "
                "(mechanism, part_id, "
                f"param_name)=({repr(mechanism)}, {part_id}, "
                f"{param_name})"
            )
        elif return_numerical and isinstance(param, Parameter):
            return param.value
        else:
            return param

    # TODO implement abstractmethod
    def update_species(self) -> List[Species]:
        """Generate and return species associated with this component.

        Returns
        -------
        list of Species
            List of species objects generated by this component. This base
            implementation returns an empty list.

        Notes
        -----
        This method should be overridden by subclasses to return the actual
        species generated by the component during CRN compilation.

        """
        species = []
        warn("Unsubclassed update_species called for " + repr(self))
        return species

    # TODO implement abstractmethod
    def update_reactions(self) -> List[Species]:
        """Generate and return reactions associated with this component.

        Returns
        -------
        list of Reaction
            List of reaction objects generated by this component. This base
            implementation returns an empty list.

        Notes
        -----
        This method should be overridden by subclasses to return the actual
        reactions generated by the component during CRN compilation.

        """
        reactions = []
        warn("Unsubclassed update_reactions called for " + repr(self))
        return reactions

    def enumerate_components(self, previously_enumerated=None) -> List:
        """Enumerate derived components created from this component.

        This method generates new components based on the current component,
        typically used during CRN compilation to expand higher-level
        components into their constituent parts and products.

        Parameters
        ----------
        previously_enumerated : set or list, optional
            Collection of components that have already been enumerated, used
            to prevent infinite recursion in component enumeration.

        Returns
        -------
        list
            List of new components created from this component. This base
            implementation returns an empty list.

        Notes
        -----
        Subclasses override this method to implement specific enumeration
        behavior. For example:

        - A `DNA_construct` returns copies of its parts and `RNA_construct`
          objects representing transcripts.
        - An `RNA_construct` returns copies of its parts and `Protein`
          components representing translation products.

        """
        return []

    def __repr__(self):
        return type(self).__name__ + ': ' + self.name
