# Copyright (c) 2020, Build-A-Cell. All rights reserved.
# See LICENSE file in the project root directory for details.

from typing import List
from warnings import warn


class Mechanism(object):
    """Base class for mechanisms that generate species and reactions.

    Mechanisms are reaction schemas that define how components interact and
    transform during CRN compilation. They represent molecular processes such
    as transcription, translation, binding, catalysis, and degradation. Each
    mechanism is called by components during compilation to generate the
    appropriate species and reactions.

    Parameters
    ----------
    name : str
        Name of the mechanism instance for identification and debugging.
    mechanism_type : str, default=''
        Type identifier for the mechanism (e.g., 'transcription',
        'translation', 'binding'). Used for mechanism lookup in components
        and mixtures.

    Attributes
    ----------
    name : str
        Name of the mechanism.
    mechanism_type : str
        Type identifier for the mechanism.

    See Also
    --------
    Component : Base class that calls mechanisms during compilation.
    Mixture : Container that provides default mechanisms to components.

    Notes
    -----
    Subclasses must override `update_species` and `update_reactions` to
    implement specific mechanism behavior. The base class implementations
    return empty lists and issue warnings.

    If `mechanism_type` is empty or None, a warning is issued as this may
    prevent proper mechanism inheritance and lookup.

    Examples
    --------
    Create a custom mechanism by subclassing:

    >>> class CustomTranscription(bcp.Mechanism):
    ...     def __init__(self, name="custom_tx"):
    ...         super().__init__(name=name, mechanism_type="transcription")
    ...
    ...     def update_species(self, dna, transcript, **kwargs):
    ...         # Generate RNA species
    ...         return [transcript]
    ...
    ...     def update_reactions(self, dna, transcript, **kwargs):
    ...         # Generate transcription reaction
    ...         return [Reaction([dna], [dna, transcript], k=0.01)]

    Use a mechanism in a mixture:

    >>> mixture = bcp.Mixture(
    ...     mechanisms={'transcription': CustomTranscription()}
    ... )

    """

    def __init__(self, name: str, mechanism_type=''):
        self.name = name
        self.mechanism_type = mechanism_type
        if mechanism_type == '' or mechanism_type is None:
            warn(
                f"Mechanism {name} instantiated without a type. This could "
                "prevent the mechanism from being inherited properly."
            )

    def update_species(self, component=None, part_id=None) -> List:
        """Generate species for this mechanism.

        Parameters
        ----------
        component : Component, optional
            The component calling this mechanism. May be used to access
            component-specific parameters or attributes.
        part_id : str, optional
            Part identifier for parameter lookup. Used to retrieve
            part-specific parameters from the parameter database.

        Returns
        -------
        list of Species
            List of species objects generated by this mechanism. This base
            implementation returns an empty list.

        Warns
        -----
        UserWarning
            Issues a warning when the base class method is called, indicating
            that subclasses should override this method.

        Notes
        -----
        Subclasses must override this method to implement mechanism-specific
        species generation logic.

        """
        warn(f"Default update_species called for mechanism {self.name}")
        return []

    def update_reactions(self, component=None, part_id=None) -> List:
        """Generate reactions for this mechanism.

        Parameters
        ----------
        component : Component, optional
            The component calling this mechanism. May be used to access
            component-specific parameters or attributes.
        part_id : str, optional
            Part identifier for parameter lookup. Used to retrieve
            part-specific parameters from the parameter database.

        Returns
        -------
        list of Reaction
            List of reaction objects generated by this mechanism. This base
            implementation returns an empty list.

        Warns
        -----
        UserWarning
            Issues a warning when the base class method is called, indicating
            that subclasses should override this method.

        Notes
        -----
        Subclasses must override this method to implement mechanism-specific
        reaction generation logic.

        """
        warn(f"Default update_reactions called for mechanism {self.name}")
        return []

    def __repr__(self):
        return self.name


class EmptyMechanism(Mechanism):
    """Mechanism that generates no species or reactions.

    A placeholder mechanism used when a mechanism type is required but no
    actual reactions should be generated. Commonly used in Expression Mixtures
    where translation is disabled, or to temporarily disable specific
    mechanisms without removing them from the code.

    Parameters
    ----------
    name : str
        Name of the mechanism instance.
    mechanism_type : str
        Type identifier for the mechanism (e.g., 'translation').

    See Also
    --------
    Mechanism : Base class for all mechanisms.

    Notes
    -----
    Both `update_species` and `update_reactions` return empty lists,
    ensuring no CRN elements are generated when this mechanism is called.

    Examples
    --------
    Use EmptyMechanism to disable translation in a mixture:

    >>> rnap = bcp.Species('RNAP')
    >>> mixture = bcp.Mixture(
    ...     mechanisms={
    ...         'transcription': bcp.Transcription_MM(rnap),
    ...         'translation': bcp.EmptyMechanism(
    ...             'no_translation', 'translation')
    ...     }
    ... )

    Create a DNA assembly that transcribes but doesn't translate:

    >>> promoter = bcp.Promoter('pconst')
    >>> assembly = bcp.DNAassembly(
    ...     name='tx_only',
    ...     promoter=promoter,
    ...     mechanisms={
    ...        'translation': bcp.EmptyMechanism('empty', 'translation')
    ...     }
    ... )

    """

    def __init__(self, name, mechanism_type):
        Mechanism.__init__(self, name=name, mechanism_type=mechanism_type)

    def update_species(self, component=None, part_id=None, **kwargs):
        """Generate no species.

        Parameters
        ----------
        component : Component, optional
            The component calling this mechanism (unused).
        part_id : str, optional
            Part identifier (unused).
        **kwargs
            Additional keyword arguments (unused).

        Returns
        -------
        list
            Empty list.

        """
        return []

    def update_reactions(self, component=None, part_id=None, **kwargs):
        """Generate no reactions.

        Parameters
        ----------
        component : Component, optional
            The component calling this mechanism (unused).
        part_id : str, optional
            Part identifier (unused).
        **kwargs
            Additional keyword arguments (unused).

        Returns
        -------
        list
            Empty list.

        """
        return []
