[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "BioCRNpyler"
dynamic = ["version"]
description = "A chemical reaction network compiler for generating large biological circuit models"
authors = [{name='Build-A-Cell'}]
classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: BSD License',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Topic :: Software Development',
        'Topic :: Scientific/Engineering',
        'Operating System :: OS Independent',
    ]
license = {file = "LICENSE"}
readme = "README.md"
keywords=["SBML", "synthetic biology", "modeling",
          "Chemical Reaction Network", "CRN"]
dependencies = [
    "python-libsbml",
    "numpy<2.0",
    "matplotlib",
    "networkx",
    "bokeh>=1.4.0",
    "fa2_modified",
    "jupyter",
    "pytest",
    "pytest-cov",
    "nbconvert"
]
requires-python = ">=3.9"

[project.optional-dependencies]
test = [
  "pytest"
]

[project.urls]
"Homepage" = "https://github.com/buildacell/biocrnpyler/"
"Bug Tracker" = "https://github.com/buildacell/biocrnpyler/issues"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["biocrnpyler", "biocrnpyler.*"]

[tool.setuptools_scm]
write_to = "biocrnpyler/_version.py"
local_scheme = "no-local-version"

[tool.ruff]
line-length = 78

[tool.ruff.lint]
select = [
       'F',			# pyflakes
       'D',			# docstyle
       'I',			# isort
       'W'			# warnings (white space, line length)
]
ignore = [
    'D100', 'D101', 'D102', 	# ignore missing docstrings for now
    'D103', 'D104', 'D105',
    'D105', 'D106', 'D107',
    'D200',			# ignore long docstring first lines for now
    'D417',			# ignore missing argument descriptions for now
]

[tool.ruff.lint.per-file-ignores]
# Ignore `D` rules everywhere except for the `biocrnpyler/` directory.
'!biocrnpyler/**.py' = ['D']
'Tests/**.py' = [
    'F841',			# unused variables OK
    'F403', 'F405',		# star imports OK
]
'examples/**.py' = [
    'F403', 'F405',		# star imports OK
]
'__init__.py' = ['F403']	# star imports OK

[tool.ruff.format]
quote-style = 'preserve'

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.isort]
profile = 'black'
line_length = 78
