# Copyright (c) 2020, Build-A-Cell. All rights reserved.
# See LICENSE file in the project root directory for details.

from ...core.chemical_reaction_network import Species
from ...core.component import Component
from .construct import DNA_part


class CDS(DNA_part):
    """Coding sequence component representing a protein-coding region.

    A CDS (coding sequence) represents a contiguous DNA sequence that codes
    for a protein product. This component stores the protein species
    associated with the coding region but does not directly generate
    translation reactions. Translation is typically handled by an RBS
    component that acts on the transcript containing this CDS.

    Parameters
    ----------
    name : str
        Name of the coding sequence.
    protein : Protein, str, Component, or None, optional
        The protein product encoded by this CDS. Can be a `Species` object,
        string name (creates a protein Species), `Component` with an
        associated species, or None (creates protein Species using CDS name).
    no_stop_codons : list, optional
        List of regions without stop codons, used for sequence validation or
        special handling of coding sequences.
    **kwargs
        Additional keyword arguments passed to the parent `DNA_part` class.

    Attributes
    ----------
    name : str
        Name of the coding sequence.
    protein : Species
        The protein species encoded by this CDS.

    See Also
    --------
    RBS : Component that controls translation of proteins.
    DNAassembly : Container for CDS and other genetic parts.
    DNA_part : Base class for DNA component parts.

    Notes
    -----
    The CDS component itself does not generate any reactions during CRN
    compilation. It serves primarily as a data structure to associate a
    coding sequence with its protein product. The actual translation
    reactions are generated by RBS components that reference the transcript
    containing this CDS.

    Examples
    --------
    Create a CDS with automatic protein naming:

    >>> cds = bcp.CDS(name='gfp')
    >>> cds.protein
    protein_gfp

    Create a CDS with explicit protein name:

    >>> cds = bcp.CDS(
    ...     name='cds_reporter',
    ...     protein='GFP_protein'
    ... )

    Use a CDS in a DNA assembly:

    >>> assembly = bcp.DNAassembly(
    ...     name='gene_construct',
    ...     promoter='pconst',
    ...     rbs='rbs1',
    ...     protein=cds
    ... )

    """

    def __init__(self, name, protein=None, no_stop_codons=[], **kwargs):
        DNA_part.__init__(self, name, no_stop_codons=no_stop_codons, **kwargs)
        # TODO use set_species()
        if protein is None:
            self.protein = Species(name, material_type='protein')
        elif isinstance(protein, str):
            self.protein = Species(protein, material_type='protein')
        elif isinstance(protein, Component):
            self.protein = protein.get_species()

    def update_species(self):
        """Generate species associated with this CDS.

        Returns
        -------
        list of Species
            List containing only the protein species encoded by this CDS.

        """
        return [self.protein]

    def update_reactions(self):
        """Generate reactions associated with this CDS.

        Returns
        -------
        list of Reaction
            Empty list. CDS components have no associated mechanism.
            Translation reactions are generated by the RBS component.

        """
        return []

    def get_species(self):
        """Get the protein species encoded by this CDS.

        Returns
        -------
        Species
            The protein species associated with this coding sequence.

        """
        return self.protein
