name: docs_pages_workflow

# execute this workflow automatically when we push to master
on:
  push:
    branches: [ master ]

jobs:

  build_docs_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:

      - name: Prereqs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          apt-get update
          apt-get install -y git
          git clone --depth 1 "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        shell: bash
        
      - name: Set up Python 
        uses: actions/setup-python@v2
        
      - name: Install python dependencies
        run: |
          pip install -r docs/requirements.txt 

      - name: Execute script to build our documentation and update pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "docs/build_docs.sh"
        shell: bash
