name: test_bioscrape
on:
  push:
    branches: ["*","!master"]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov python-libsbml
      - name: Tnstall biocrnpyler
        run: pip install -e .[all]
      - name: Test biocrnpyler
        run: pytest --cov biocrnpyler
      - uses: actions/checkout@main
      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false 
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }} 
          verbose: false
